import 'dart:io';
import 'dart:convert';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart' show SharePlus, XFile, ShareParams;
import 'package:archive/archive_io.dart';
import 'package:smart_scan/shared/models/scan_model.dart';
import 'notification_service.dart';

/// Service for exporting scans to various formats (PDF, TXT, DOCX).
/// After each export a system notification is shown. Tapping the notification
/// opens the exported file with the default app.
class ExportService {
  static final ExportService _instance = ExportService._internal();

  factory ExportService() => _instance;
  ExportService._internal();

  // ─── Public API ────────────────────────────────────────────────────────────

  /// Export scan to PDF. Returns the saved file path.
  Future<String> exportToPDF(ScanModel scan) async {
    try {
      final pdf = pw.Document();
      pdf.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(40),
          build: (pw.Context ctx) => pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                scan.title,
                style:
                    pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold),
              ),
              pw.SizedBox(height: 4),
              pw.Text(
                'Exported: ${_formatDate(scan.createdAt)}',
                style:
                    const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
              ),
              pw.Divider(thickness: 1),
              pw.SizedBox(height: 12),
              _pdfSection(ctx, 'Scan Information', [
                'Detected Language: ${scan.detectedLanguage ?? "N/A"}',
                'Target Language:   ${scan.targetLanguage ?? "N/A"}',
                if (scan.categoryId != null)
                  'Category ID:       ${scan.categoryId}',
              ]),
              pw.SizedBox(height: 12),
              _pdfSection(
                  ctx, 'Original Text', [scan.rawText ?? 'No text extracted']),
              if (scan.translatedText != null &&
                  scan.translatedText!.isNotEmpty) ...[
                pw.SizedBox(height: 12),
                _pdfSection(ctx, 'Translated Text', [scan.translatedText!]),
              ],
              pw.Spacer(),
              pw.Divider(thickness: 0.5),
              pw.Text('Generated by SmartScan',
                  style:
                      const pw.TextStyle(fontSize: 8, color: PdfColors.grey)),
            ],
          ),
        ),
      );

      final fileName = '${_sanitize(scan.title)}.pdf';
      final filePath = await _getSaveLocation(fileName);
      await File(filePath).writeAsBytes(await pdf.save());

      await NotificationService().showExportNotification(
        fileName: fileName,
        exportFormat: 'PDF',
        filePath: filePath,
      );
      return filePath;
    } catch (e) {
      throw Exception('PDF export failed: $e');
    }
  }

  /// Export scan to plain text (.txt). Returns the saved file path.
  Future<String> exportToTXT(ScanModel scan) async {
    try {
      final content = _buildTextContent(scan);
      final fileName = '${_sanitize(scan.title)}.txt';
      final filePath = await _getSaveLocation(fileName);
      await File(filePath).writeAsString(content, encoding: utf8);

      await NotificationService().showExportNotification(
        fileName: fileName,
        exportFormat: 'TXT',
        filePath: filePath,
      );
      return filePath;
    } catch (e) {
      throw Exception('TXT export failed: $e');
    }
  }

  /// Export scan to Word document (.docx). Returns the saved file path.
  /// Creates a valid Open XML DOCX archive.
  Future<String> exportToWord(ScanModel scan) async {
    try {
      final bytes = _buildDocxBytes(
        title: scan.title,
        createdAt: scan.createdAt,
        detectedLanguage: scan.detectedLanguage ?? 'N/A',
        targetLanguage: scan.targetLanguage ?? 'N/A',
        rawText: scan.rawText ?? 'No text extracted',
        translatedText: scan.translatedText,
      );
      final fileName = '${_sanitize(scan.title)}.docx';
      final filePath = await _getSaveLocation(fileName);
      await File(filePath).writeAsBytes(bytes);

      await NotificationService().showExportNotification(
        fileName: fileName,
        exportFormat: 'DOCX',
        filePath: filePath,
      );
      return filePath;
    } catch (e) {
      throw Exception('DOCX export failed: $e');
    }
  }

  /// Export saved translation to various formats
  Future<String> exportTranslation({
    required String title,
    required String originalText,
    required String translatedText,
    required String sourceLanguage,
    required String targetLanguage,
    required String format,
  }) async {
    try {
      final fileName = '${_sanitize(title)}.$format';
      final filePath = await _getSaveLocation(fileName);

      if (format == 'pdf') {
        final pdf = pw.Document();
        pdf.addPage(
          pw.Page(
            pageFormat: PdfPageFormat.a4,
            margin: const pw.EdgeInsets.all(40),
            build: (pw.Context ctx) => pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  title,
                  style: pw.TextStyle(
                      fontSize: 22, fontWeight: pw.FontWeight.bold),
                ),
                pw.SizedBox(height: 4),
                pw.Text(
                  'Exported: ${_formatDate(DateTime.now())}',
                  style:
                      const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
                ),
                pw.Divider(thickness: 1),
                pw.SizedBox(height: 12),
                _pdfSection(ctx, 'Translation Information', [
                  'Source Language: $sourceLanguage',
                  'Target Language: $targetLanguage',
                ]),
                pw.SizedBox(height: 12),
                _pdfSection(ctx, 'Original Text', [originalText]),
                pw.SizedBox(height: 12),
                _pdfSection(ctx, 'Translated Text', [translatedText]),
                pw.Spacer(),
                pw.Divider(thickness: 0.5),
                pw.Text('Generated by SmartScan',
                    style:
                        const pw.TextStyle(fontSize: 8, color: PdfColors.grey)),
              ],
            ),
          ),
        );
        await File(filePath).writeAsBytes(await pdf.save());
      } else if (format == 'docx') {
        final bytes = _buildDocxBytes(
          title: title,
          createdAt: DateTime.now(),
          detectedLanguage: sourceLanguage,
          targetLanguage: targetLanguage,
          rawText: originalText,
          translatedText: translatedText,
        );
        await File(filePath).writeAsBytes(bytes);
      } else if (format == 'xml') {
        final content = _buildXmlContent(
          title: title,
          originalText: originalText,
          translatedText: translatedText,
          sourceLanguage: sourceLanguage,
          targetLanguage: targetLanguage,
        );
        await File(filePath).writeAsString(content, encoding: utf8);
      } else {
        throw Exception('Unsupported format: $format');
      }

      await NotificationService().showExportNotification(
        fileName: fileName,
        exportFormat: format.toUpperCase(),
        filePath: filePath,
      );

      return filePath;
    } catch (e) {
      throw Exception('Translation export failed: $e');
    }
  }

  // ─── File Management ────────────────────────────────────────────────────────

  Future<List<File>> getExportedFiles() async {
    try {
      final folder = await _getSmartScanFolder();
      if (!await folder.exists()) return [];
      return folder.listSync().whereType<File>().toList()
        ..sort(
            (a, b) => b.statSync().modified.compareTo(a.statSync().modified));
    } catch (_) {
      return [];
    }
  }

  Future<void> deleteExportedFile(String filePath) async {
    final f = File(filePath);
    if (await f.exists()) await f.delete();
  }

  Future<void> shareFile(String filePath, {String? subject}) async {
    final f = File(filePath);
    if (!await f.exists()) throw Exception('File not found: $filePath');
    await SharePlus.instance.share(
      ShareParams(
        files: [XFile(filePath)],
        subject: subject ?? 'SmartScan Export',
      ),
    );
  }

  Future<String> getOpenableFilePath(String filePath) async {
    if (!await File(filePath).exists()) {
      throw Exception('File not found: $filePath');
    }
    return filePath;
  }

  // ─── Helpers ────────────────────────────────────────────────────────────────

  pw.Widget _pdfSection(pw.Context ctx, String heading, List<String> lines) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(heading,
            style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold)),
        pw.SizedBox(height: 6),
        ...lines.map(
          (l) => pw.Padding(
            padding: const pw.EdgeInsets.only(bottom: 4),
            child: pw.Text(l, style: const pw.TextStyle(fontSize: 11)),
          ),
        ),
      ],
    );
  }

  String _buildTextContent(ScanModel scan) {
    final b = StringBuffer();
    b.writeln('═' * 60);
    b.writeln(scan.title);
    b.writeln('═' * 60);
    b.writeln('Exported : ${_formatDate(scan.createdAt)}');
    b.writeln('Detected : ${scan.detectedLanguage ?? "N/A"}');
    b.writeln('Target   : ${scan.targetLanguage ?? "N/A"}');
    if (scan.categoryId != null) b.writeln('Category : ${scan.categoryId}');
    b.writeln('─' * 60);
    b.writeln('ORIGINAL TEXT');
    b.writeln('─' * 60);
    b.writeln(scan.rawText ?? 'No text extracted');
    if (scan.translatedText != null && scan.translatedText!.isNotEmpty) {
      b.writeln();
      b.writeln('─' * 60);
      b.writeln('TRANSLATED TEXT');
      b.writeln('─' * 60);
      b.writeln(scan.translatedText!);
    }
    b.writeln();
    b.writeln('═' * 60);
    b.writeln('Generated by SmartScan');
    return b.toString();
  }

  String _buildXmlContent({
    required String title,
    required String originalText,
    required String translatedText,
    required String sourceLanguage,
    required String targetLanguage,
  }) {
    final b = StringBuffer();
    b.writeln('<?xml version="1.0" encoding="UTF-8"?>');
    b.writeln('<translation_export>');
    b.writeln('  <metadata>');
    b.writeln('    <title>${_escapeXml(title)}</title>');
    b.writeln('    <date>${_escapeXml(_formatDate(DateTime.now()))}</date>');
    b.writeln(
        '    <source_language>${_escapeXml(sourceLanguage)}</source_language>');
    b.writeln(
        '    <target_language>${_escapeXml(targetLanguage)}</target_language>');
    b.writeln('  </metadata>');
    b.writeln('  <content>');
    b.writeln('    <original_text>${_escapeXml(originalText)}</original_text>');
    b.writeln(
        '    <translated_text>${_escapeXml(translatedText)}</translated_text>');
    b.writeln('  </content>');
    b.writeln('  <footer_info>Generated by SmartScan</footer_info>');
    b.writeln('</translation_export>');
    return b.toString();
  }

  /// Builds a minimal but valid Open XML DOCX archive.
  List<int> _buildDocxBytes({
    required String title,
    required DateTime createdAt,
    required String detectedLanguage,
    required String targetLanguage,
    required String rawText,
    String? translatedText,
  }) {
    final archive = Archive();

    void addFile(String name, String content) {
      final bytes = utf8.encode(content);
      archive.addFile(
        ArchiveFile(name, bytes.length, bytes),
      );
    }

    // [Content_Types].xml
    addFile('[Content_Types].xml',
        '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
</Types>''');

    // _rels/.rels
    addFile('_rels/.rels',
        '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>''');

    // word/_rels/document.xml.rels
    addFile('word/_rels/document.xml.rels',
        '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
</Relationships>''');

    // word/document.xml
    final escapedTitle = _escapeXml(title);
    final escapedDate = _escapeXml(_formatDate(createdAt));
    final escapedDetected = _escapeXml(detectedLanguage);
    final escapedTarget = _escapeXml(targetLanguage);
    final rawLines = (rawText).split('\n');
    final rawParagraphs =
        rawLines.map((l) => _xmlParagraph(_escapeXml(l))).join('\n');

    String translatedSection = '';
    if (translatedText != null && translatedText.isNotEmpty) {
      final tLines = translatedText.split('\n');
      final tParagraphs =
          tLines.map((l) => _xmlParagraph(_escapeXml(l))).join('\n');
      translatedSection = '''
    ${_xmlHeading('Translated Text')}
    $tParagraphs''';
    }

    addFile('word/document.xml',
        '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas"
            xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"
            xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <w:body>
    ${_xmlHeading(escapedTitle)}
    ${_xmlParagraph('Exported: $escapedDate')}
    ${_xmlParagraph('Detected Language: $escapedDetected')}
    ${_xmlParagraph('Target Language: $escapedTarget')}
    ${_xmlParagraph('')}
    ${_xmlHeading('Original Text')}
    $rawParagraphs
    $translatedSection
    ${_xmlParagraph('')}
    ${_xmlParagraph('Generated by SmartScan')}
    <w:sectPr/>
  </w:body>
</w:document>''');

    final encoder = ZipEncoder();
    return encoder.encode(archive);
  }

  String _xmlHeading(String text) => '''<w:p>
      <w:pPr><w:pStyle w:val="Heading1"/></w:pPr>
      <w:r><w:t xml:space="preserve">$text</w:t></w:r>
    </w:p>''';

  String _xmlParagraph(String text) => '''<w:p>
      <w:r><w:t xml:space="preserve">$text</w:t></w:r>
    </w:p>''';

  String _escapeXml(String s) => s
      .replaceAll('&', '&amp;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;')
      .replaceAll('"', '&quot;')
      .replaceAll("'", '&apos;');

  Future<String> _getSaveLocation(String fileName) async {
    final folder = await _getSmartScanFolder();
    if (!await folder.exists()) await folder.create(recursive: true);
    return '${folder.path}/$fileName';
  }

  Future<Directory> _getSmartScanFolder() async {
    if (Platform.isAndroid) {
      // Prefer public Downloads folder
      final dl = Directory('/storage/emulated/0/Download/SmartScan');
      try {
        if (!await dl.exists()) await dl.create(recursive: true);
        return dl;
      } catch (_) {}
      // Fallback: external app directory
      final ext = await getExternalStorageDirectory();
      if (ext != null) {
        final d = Directory('${ext.path}/SmartScan');
        if (!await d.exists()) await d.create(recursive: true);
        return d;
      }
    }
    // iOS / fallback
    final docs = await getApplicationDocumentsDirectory();
    final d = Directory('${docs.path}/SmartScan');
    if (!await d.exists()) await d.create(recursive: true);
    return d;
  }

  String _sanitize(String name) =>
      name.replaceAll(RegExp(r'[\\/:*?"<>|]'), '_').trim();

  String _formatDate(DateTime d) =>
      '${d.year}-${_p(d.month)}-${_p(d.day)} ${_p(d.hour)}:${_p(d.minute)}:${_p(d.second)}';

  String _p(int n) => n.toString().padLeft(2, '0');
}
